/**
 * Created by William on 5/3/2017.
 */

 module.exports = {
     "A1" : [
         { "name" : { "value": "das Buch"}},
         { "name" : { "value": "kommen"}},
         { "name" : { "value": "sehen"}},
         { "name" : { "value": "trinken"}},
         { "name" : { "value": "die Schule"}},
         { "name" : { "value": "die Sprache"}},
         { "name" : { "value": "das Auto"}},
         { "name" : { "value": "lesen"}},
         { "name" : { "value": "arbeiten"}},
         { "name" : { "value": "essen"}},
         { "name" : { "value": "das Wohnzimmer"}},
         { "name" : { "value": "übersetzen"}},
         { "name" : { "value": "probieren"}},
         { "name" : { "value": "kennenlernen"}},
         { "name" : { "value": "der Zahnarzt"}},
         { "name" : { "value": "die Schuhe"}},
         { "name" : { "value": "fahren"}},
         { "name" : { "value": "verkaufen"}},
         { "name" : { "value": "die Gesundheit"}},
         { "name" : { "value": "spazieren"}},
         { "name" : { "value": "der Bruder"}},
         { "name" : { "value": "die Schwester"}},
         { "name" : { "value": "der Sohn"}},
         { "name" : { "value": "die Tochter"}},
         { "name" : { "value": "die Geschwister"}},
         { "name" : { "value": "ein Einzelkind"}},
         { "name" : { "value": "der Schüler"}},
         { "name" : { "value": "die Ausbildung"}},
         { "name" : { "value": "der Elektriker"}},
         { "name" : { "value": "die Arbeit"}},
         { "name" : { "value": "die Bücher"}},
         { "name" : { "value": "der Geburtstag"}},
         { "name" : { "value": "die Heimat"}},
         { "name" : { "value": "das Hobby"}},
         { "name" : { "value": "der Name"}},
         { "name" : { "value": "Guten Morgen"}},
         { "name" : { "value": "Guten Tag"}},
         { "name" : { "value": "Guten Abend"}},
         { "name" : { "value": "Guten Tag. Mein Name ist Schmidt."}},
         { "name" : { "value": "Wie geht es dir?"}},
         { "name" : { "value": "Auf Wiedersehen"}},
         { "name" : { "value": "Tschüss"}},
         { "name" : { "value": "Bis morgen"}},
         { "name" : { "value": "Bis später"}},
         { "name" : { "value": "Bis heute Abend"}},
         { "name" : { "value": "Danke"}},

     ],

     "B1" : [
         { "name" : { "value": "die Verantwortung"}},
         { "name" : { "value": "der Geburtstag"}},
         { "name" : { "value": "das Taschengeld"}},
         { "name" : { "value": "geschlossen"}},
         { "name" : { "value": "das Gewitter"}},
         { "name" : { "value": "der Kopfschmerz"}},
         { "name" : { "value": "das Mittagessen"}},
         { "name" : { "value": "der Ausländer"}},
         { "name" : { "value": "transportieren"}},
         { "name" : { "value": "das Wörterbuch"}},
         { "name" : { "value": "mittlerweile"}},
         { "name" : { "value": "offensichtlich"}},
         { "name" : { "value": "die Ausländerbehörde"}},
         { "name" : { "value": "Hoffentlich"}},
         { "name" : { "value": "genießen"}},
         { "name" : { "value": "die Abteilung"}},
         { "name" : { "value": "die Schularbeit"}},
         { "name" : { "value": "durchführen"}},
         { "name" : { "value": "die Abwanderung"}},
         { "name" : { "value": "der Kreisverkehr"}},
         { "name" : { "value": "das Abo"}},
         { "name" : { "value": "das Abonnement"}},
         { "name" : { "value": "der Akku"}},
         { "name" : { "value": "der Akkumulator"}},
         { "name" : { "value": "die Batterie"}},
         { "name" : { "value": "der Azubi"}},
         { "name" : { "value": "der Auszubildende"}},
         { "name" : { "value": "circa"}},
         { "name" : { "value": "die DVD"}},
         { "name" : { "value": "Datenträger"}},
         { "name" : { "value": "das Erdgeschoss"}},
         { "name" : { "value": "das Obergeschoss"}},
         { "name" : { "value": "das Untergeschoss"}},
         { "name" : { "value": "et cetera"}},
         { "name" : { "value": "der Inter City Express"}},
         { "name" : { "value": "das Kraftfahrzeug"}},
         { "name" : { "value": "der Lastwagen"}},
         { "name" : { "value": "der Personal Computer"}},
         { "name" : { "value": "der Personenkraftwagen"}},
         { "name" : { "value": "Textnachricht"}},
         { "name" : { "value": "Television"}},
         { "name" : { "value": "und so weiter"}},
         { "name" : { "value": "vergleiche"}},
         { "name" : { "value": "Wasserklosett"}},
         { "name" : { "value": "die Wohngemeinschaft"}},
         { "name" : { "value": "zum Beispiel"}},

     ],

     "C1" : [
         { "name" : { "value": "die Rechtsanwältin"}},
         { "name" : { "value": "vernünftig"}},
         { "name" : { "value": "das Mitgefühl"}},
         { "name" : { "value": "der Sauerstoff"}},
         { "name" : { "value": "der Wissenschaftler"}},
         { "name" : { "value": "währenddessen"}},
         { "name" : { "value": "die Atmosphäre"}},
         { "name" : { "value": "reduzieren"}},
         { "name" : { "value": "zurechtfinden"}},
         { "name" : { "value": "die Deutschkenntnisse"}},
         { "name" : { "value": "die Rechtschreibprüfung"}},
         { "name" : { "value": "die Schadenfreude"}},
         { "name" : { "value": "die Streichholzschachtel"}},
         { "name" : { "value": "experimentieren"}},
         { "name" : { "value": "der Reißverschluss"}},
         { "name" : { "value": "die Bundeswehr"}},
         { "name" : { "value": "die Maßeinheit"}},
         { "name" : { "value": "der Geschäftsführer"}},
         { "name" : { "value": "mitwirken"}},
         { "name" : { "value": "die Versicherung"}},
         { "name" : { "value": "im Vorteil"}},
         { "name" : { "value": "von Vorteil"}},
         { "name" : { "value": "Zuzüglich"}},
         { "name" : { "value": "Beiläufig"}},
         { "name" : { "value": "Zunehmend"}},
         { "name" : { "value": "Ergänzend"}},
         { "name" : { "value": "Umfassende"}},
         { "name" : { "value": "Weite"}},
         { "name" : { "value": "Umgängliche"}},
         { "name" : { "value": "entschlossenen"}},
         { "name" : { "value": "verheissen"}},
         { "name" : { "value": "vermitteln"}},
         { "name" : { "value": "diesbezüglich"}},
         { "name" : { "value": "inwieweit"}},
         { "name" : { "value": "Auswirkungen"}},
         { "name" : { "value": "etikettiert"}},
         { "name" : { "value": "die Medikamente"}},
         { "name" : { "value": "Lösungsvorschlägen"}},
         { "name" : { "value": "Pharmaproduzenten"}},
         { "name" : { "value": "der Koffer"}},
         { "name" : { "value": "der Gesprächspartner"}},
         { "name" : { "value": "die Fachzeitschriften"}},
         { "name" : { "value": "die Dokumentation"}},
         { "name" : { "value": "Produktionsprozesse"}},
         { "name" : { "value": "mitzuarbeiten"}},
         { "name" : { "value": "Außendienst"}},
         { "name" : { "value": "Vertriebstätigkeit"}}
     ]
 }
